### ISSUE TITLE
some trouble to use more than 3 dimmers in RAMP MODE.

### ISSUE THREAD

**Issue by junior700** [circuitar/Dimmer#10]
Boa tarde: 
    Antes de mais nada gostaríamos de parabenizar sobre o excelente trabalho em criar a bilbioteca Dimmer.h, já que ha bastante tempo estava buscando algum recurso viável e de fácil utilização para a plataforma Arduino. 
    Utilizei a sua bilbioteca em alguns scketchs, e notei uma coisa: 
No modo NORMAL_MODE, consegui utilizar todos os 10 dimmers e ainda assim mantive incólume a comunicação serial. Porém, ao tentar usar mais de dois dimmers no modo RAMP_MODE, em conjunto com a comunicação serial nativa do arduino, a mesma simplesmente perde a funcionalidade. Até a habilitação do segundo dimmer não tive nenhum problema, mas a partir do terceiro dimmer ele não mais responde. Sabe se haveria algum remédio para este efeito indesejável? Vejo que vocês usaram o TIMER2 na bilbioteca, e até aonde eu sei o uso dele não é usado na USART que controla a serial.  
    Já percebi que, mesmo antes de usar a bilbioteca de vocês, o uso da serial fica um pouco limitado, independente se usar-se o TIMER1, TIMER2 ou sem o uso do timer ( sem o uso dos timers é bem pior porque a temporização é feita dentro da interrupção gerada pelo sensor zerocross, e sobra muito pouco tempo para o microcontroller executar todas as outras tarefas), tinha esperança que esta sua bilbioteca não tivesse esta mesma limitação (embora ela seja superior aos outros métodos usados até hoje por mim). 
    Sei que vocês não tem obrigação de darem suporte ao uso dessa biblioteca, mas se puder dar uma dica de como contornar isso, agradeço muito.
 
Helio

**Comment by alexsartin** [comment]
Em relação ao tempo de processamento nas interrupções, você pode testar a biblioteca antiga, que faz bem menos cálculos na interrupção do zero_cross para o RAMP_MODE. Além disso ela cria apenas uma objeto para todos os tricas utilizados no projeto, diminuindo o processamento em aproximadamente N vezes, sendo N o número de triacs utilizados.
Link: [Dimmer Versão 1](https://github.com/circuitar/Dimmer/tree/b2f74da599d5a3dc12287bf3e169d77f9c933a36)
Olhar os arquivos de exemplo dessa versão, pois como apenas um objeto controla todos os triacs, o acionamento na versão anterior é completamente diferente da versão atual.

**Comment by junior700** [comment]
Obrigado Alex pelo retorno, porém ao rodar um dos exemplos ( DisplayLamps ) aparece o seguinte erro, parece que "Dimmer" não é reconhecido como uma classe:

Arduino: 1.6.5 (Windows XP), Placa:"Arduino/Genuino Uno"

DisplayLamps:16: error: 'Dimmer' does not name a type
DisplayLamps.ino: In function 'void setup()':
DisplayLamps:30: error: 'dimmer1' was not declared in this scope
DisplayLamps.ino: In function 'void loop()':
DisplayLamps:39: error: 'dimmer1' was not declared in this scope
DisplayLamps.ino: In function 'void wave1(short int, byte)':
DisplayLamps:51: error: 'dimmer1' was not declared in this scope
DisplayLamps.ino: In function 'void wave2(short int, byte)':
DisplayLamps:62: error: 'dimmer1' was not declared in this scope
DisplayLamps.ino: In function 'void OnOff(short int, byte)':
DisplayLamps:73: error: 'dimmer1' was not declared in this scope
'Dimmer' does not name a type

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by lfchavier** [comment]
@junior700 colocamos uma nova versão da biblioteca no ar com processamento bem mais rápido de interrupções, veja se funciona legal para você. Tem um exemplo novo com 10 lâmpadas também.

**Comment by junior700** [comment]
Caros Luis e Alex, muitissimo obrigado pelo empenho em nos atender. Foi de grande ajuda, e o problema foi resolvido.
