### ISSUE TITLE
Add ArduinoDocs

### ISSUE THREAD

**Issue by lfchavier** [circuitar/Dimmer#5]
* Make sure to use new folder structure with "extras/docs" for ArduinoDocs files and "src" folder for .h/.cpp
  * Use Nanoshield_LCD as an example
* Update README
  * Convert README.md (Markdown) to README.rst (ResStructuredText)
  * Use README from Nanoshield_LoadCell as an example.
* Add library.properties

**Comment by alexsartin** [comment]
Fixed
